# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: MEMO-RISER
email: chrisbo246@gmail.com
description: >
  Listes de vocabulaire Français, Anglais et Russe regroupant mots composés et
  expressions courantes difficile à apprendre autrement que par la pratique.
baseurl: "/memo-riser" # the subpath of your site, e.g. /blog
url: "https://chrisbo246.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: chrisbo246
github_username:  chrisbo246

# Build settings
markdown: kramdown
theme: minima
#remote_theme: mmistakes/minimal-mistakes

# https://pages.github.com/versions/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - wdm
  - jekyll-github-metadata
  - jekyll-seo-tag
  #- jekyll-mentions # Issue with structured data
  - jekyll-sitemap


sass:
  style: compressed
  load_paths:
    - _sass
    - bower_components



# ------------------------------------------------------------------------------
# Include / Exclude / Path
# ------------------------------------------------------------------------------

# Jekyll files
# source: demo

# Compiled website
# destination: demo/site

# Do not compile and copy this files to the destination directory (_site) when running jekyll build
exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - package-lock.json
  - README.md
  - screenshot.jpg
  - screenshot.png
  - bower.json
  - node_modules
  - bower_components/**/*.md
  - bower_components/**/*.htm
  - bower_components/**/*.html
  - bower_components/**/*.lock
  - bower_components/**/.*
  - bower_components/**/bower.json
  - bower_components/**/package.json
  - bower_components/**/package-lock.json
  - bower_components/**/gulpfile.js
  - bower_components/**/Gemfile
  - bower_components/**/docs
  - bower_components/**/examples
  - bower_components/**/src
  - bower_components/**/source
  - bower_components/**/less
  - bower_components/**/external

# Copy (jekyll defaults and previously) excluded files to the destination directory when running jekyll build
include:
  - .htaccess
  - bower_components
  #- bower_components/**/build
  #- bower_components/**/dist
  #- bower_components/**/scss
  #- bower_components/**/fonts

# Do not delete/copy this (static) files from/to the destination directory each time you're running jekyll build (improve build time)
keep_files:
  - assets/images
  - assets/sounds

# Get build time details.
# bundle exec jekyll serve --profile
# Improve build time building only changed files
# bundle exec jekyll serve --incremental
# Build only the last changed posts (for large sites)
# bundle exec jekyll serve --watch --limit_posts 10


# ------------------------------------------------------------------------------
# Collections & defaults
# ------------------------------------------------------------------------------

collections:
  #categories:
  #  output: true
  #tags:
  #  output: true
  alerts:
    output: true
  helps:
    output: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      #paths: []
      type: ""
    values:
      author: chrisbo246
      publisher: chrisbo246
      date: 2017-01-01 00:00:00 +0100
  -
    scope:
      path: "assets/images"
    values:
      image: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      comments: false
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      author: chrisbo246
      publisher: chrisbo246
      comments: true
      permalink: /:categories/:title.html
      #permalink: /:categories/:short_year:month:day-:title.html
      #image:
        #path: "assets/images/posts/english-dictionary.jpg"
        #twitter: "assets/images/posts/english-dictionary.jpg"
        #facebook: "assets/images/posts/english-dictionary.jpg"
        #type: "ImageObject"
        #width: 640
        #height: 360
  -
    scope:
      path: "_categories"
      type: "categories"
    values:
      layout: "category"
      permalink: /categories/:title.html
  -
    scope:
      path: "_tags"
      type: "tags"
    values:
      layout: "tag"
      permalink: /tags/:title.html
  -
    scope:
      path: "_posts/anglais"
      type: "posts"
    values:
      definition-lang: "en-us"
  -
    scope:
      path: "_posts/russe"
      type: "posts"
    values:
      definition-lang: "ru-ru"
      alerts: ["_alerts/2017-10-28-prononciation-russe.md"]



# ------------------------------------------------------------------------------
# Plugins
# ------------------------------------------------------------------------------

# https://github.com/jekyll/minima
lang: fr
google_analytics: "UA-93687641-1"
disqus:
  shortname: memo-riser

# https://github.com/jekyll/github-metadata
repository: chrisbo246/memo-riser
github:
  url: https://chrisbo246.github.io/memo-riser/

# https://github.com/jekyll/jekyll-seo-tag
date: 2017-01-01 00:00:00 +0100
webmaster_verifications:
  google: "LSqjMgoaH49gx_-zumYmG_-wXfT619s2Eubol5bNTUA"
  bing: ""
  alexa: ""
  yandex: ""
author: chrisbo246
#  default: chrisbo2461
#  twitter: chrisbo2462
logo: assets/images/logos/android-chrome-512x512.png
twitter:
  username:
facebook:
  app_id:
  publisher:
  admins:
social:
  name: "MEMO-RISER"
  links:
    - https://github.com/memo-riser
    #- https://twitter.com/memo-riser
    #- https://www.facebook.com/memo.riser
    #- https://www.linkedin.com/in/memo-riser
    #- https://plus.google.com/+memo-riser
    #- https://keybase.io/memo-riser

# jekyll-compress-html
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  startings: all
  endings: all



# ------------------------------------------------------------------------------
# Custom
# ------------------------------------------------------------------------------

array: []
theme_color: '#ffffff'
headers:
  api-user-agent: memo-riser/1.0
  origin: https://chrisbo246.github.io/memo-riser

yandex_translate:
  key: 'trnsl.1.1.20170126T174835Z.60d9a0f54ac44aef.fc3b4dab14cf7c81caf5fe57769a769ab427a872'
  auto_mode: true
  widget_theme: 'light'

adsense:
  client: 'ca-pub-8495719252049968'
  slot: '3723415549'
  format: 'auto'
