# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: MEMOLINGUO
email: chrisbo246@gmail.com
description: >
  Listes de vocabulaire Français, Anglais et Russe regroupant mots composés et
  expressions courantes difficile à apprendre autrement que par la pratique.
baseurl: "/memolinguo" # the subpath of your site, e.g. /blog
url: "https://chrisbo246.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: chrisbo246
github_username:  chrisbo246

# Build settings
markdown: kramdown
theme: minima
#theme: jekyll-theme-cayman

# https://pages.github.com/versions/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - wdm
  - jekyll-github-metadata
  - jekyll-seo-tag
  #- jekyll-mentions # Issue with structured data
  - jekyll-sitemap


sass:
  style: compressed
#  sass_dir: _sass
  load_paths:
    - _sass
    - bower_components/bootstrap/scss
    - bower_components/font-awesome/scss


# ------------------------------------------------------------------------------
# Include / Exclude / Path
# ------------------------------------------------------------------------------

# Jekyll files
# source: demo

# Compiled website
# destination: demo/site

# Do not compile and copy this files to the destination directory (_site) when running jekyll build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - screenshot.jpg
  - bower.json
  - node_modules
  - bower_components/*.md
  - bower_components/*.html
  - bower_components/**/docs

# Copy previously excluded files to the destination directory when running jekyll build
include:
  - .htaccess
  - bower_components

# Do not delete this manually moved files from the destination directory when running jekyll build
keep_files:
#  -



# ------------------------------------------------------------------------------
# Collections & defaults
# ------------------------------------------------------------------------------

collections:
  #categories:
  #  output: true
  #tags:
  #  output: true
  definition_lists:
    output: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      #paths: []
      type: ""
    values:
      author: chrisbo246
      publisher: chrisbo246
      date: 2017-01-01 00:00:00 +0100
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      author: chrisbo246
      publisher: chrisbo246
      comments: true
      #image:
        #path: "assets/images/posts/english-dictionary.jpg"
        #twitter: "assets/images/posts/english-dictionary.jpg"
        #facebook: "assets/images/posts/english-dictionary.jpg"
        #type: "ImageObject"
        #width: 640
        #height: 360
  -
    scope:
      path: "_categories"
      type: categories
    values:
      layout: "category"
      permalink: /categories/:title.html
  -
    scope:
      path: "_tags"
      type: tags
    values:
      layout: "tag"
      permalink: /tags/:title.html
  -
    scope:
      path: ""
      type: "definition_lists"
    values:
      layout: "definition-list"
      permalink: /:categories/:title.html
      comments: true
  -
    scope:
      path: "_posts/fr"
      type: "posts"
    values:
      layout: "definition-lists"
      permalink: /:categories/:title.html
      categories: ["francais"]
      definition-lang: "fr-fr"
  -
    scope:
      path: "_posts/fr-en"
      type: "posts"
    values:
      layout: "definition-lists"
      permalink: /:categories/:title.html
      categories: ["anglais"]
      definition-lang: "en-us"
  -
    scope:
      path: "_posts/fr-ru"
      type: "posts"
    values:
      layout: "definition-lists"
      permalink: /:categories/:title.html
      categories: ["russe"]
      definition-lang: "ru-ru"



# ------------------------------------------------------------------------------
# Plugins
# ------------------------------------------------------------------------------

# https://github.com/jekyll/minima
lang: fr
google_analytics: "UA-93687641-1"
disqus:
  shortname: memolinguo

# https://github.com/jekyll/github-metadata
repository: chrisbo246/memolinguo
github:
  url: https://chrisbo246.github.io/memolinguo/

# https://github.com/jekyll/jekyll-seo-tag
date: 2017-01-01 00:00:00 +0100
webmaster_verifications:
  google: "LSqjMgoaH49gx_-zumYmG_-wXfT619s2Eubol5bNTUA"
  bing: ""
  alexa: ""
  yandex: ""
author: chrisbo246
#  default: chrisbo2461
#  twitter: chrisbo2462
logo: assets/images/logos/android-chrome-512x512.png
twitter:
  username: memolinguo
facebook:
  app_id:
  publisher:
  admins:
social:
  name: "MEMOLINGUO"
  links:
    - https://github.com/memolinguo
    #- https://twitter.com/memolinguo
    #- https://www.facebook.com/memo.linguo
    #- https://www.linkedin.com/in/memolinguo
    #- https://plus.google.com/+memolinguo
    #- https://keybase.io/memolinguo

# jekyll-compress-html
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  startings: all
  endings: all



# ------------------------------------------------------------------------------
# Custom
# ------------------------------------------------------------------------------

array: []
headers:
  api-user-agent: mediawiki-loader/1.0
  origin: https://chrisbo246.github.io/memolinguo

yandex_translate:
  key: 'trnsl.1.1.20170126T174835Z.60d9a0f54ac44aef.fc3b4dab14cf7c81caf5fe57769a769ab427a872'
  auto_mode: true
  widget_theme: 'light'

adsense:
  client: 'ca-pub-8495719252049968'
  slot: '3723415549'
  format: 'auto'
